#!/bin/zsh

pnmixer &
xfce4-volumed &
xfce4-power-manager &
thunar --daemon &
clipit &
nm-applet &

while true
do
    xsetroot -name "$(itime.py) $(date +"%a %b %d %R")"
    sleep 60
done &

exec dwm
